name: Publish Package
run-name: Build and Publish @oneezy/ui

on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Set Git user email
        run: echo "::set-env name=GIT_AUTHOR_EMAIL::${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
      - name: Set Git username
        run: echo "::set-env name=GIT_AUTHOR_NAME::${{ secrets.GITHUB_ACTOR }}"
      - name: Bump Version
        run: pnpm version patch
      - name: Build Package
        run: pnpm build
      - name: Publish Package
        run: cd package && npm publish --access public
      - name: Go Back To Root
        run: cd ..